. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\CONFIRM-PASSORD.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\GET-OU.PS1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\FORMAT-BRUKERNAVN.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\SET-BRUKERNAVN.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\NEW-POSTBOKSCSV.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\NEW-POSTBOKS.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\TEST-POSTBOKSNAVN.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\TEST-POSTBOKSALIAS.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\TEST-POSTBOKS.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\TEST-ADBRUKER.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\ADD-SENDPAVEGNEAV.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\ADD-RETTIGHETERTILPOSTBOKS.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\SET-RETTIGHETER.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\NEW-DELTPOSTBOKS.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\NEW-KONTAKTLISTE.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\ADD-BRUKERTILKONTAKTLISTE.ps1
. C:\Git-PowershellSkript\IIE-26E\ExchangeGamleScripts\REMOVE-POSTBOKS.ps1
